server:
  port: 8010
spring:
  application:
    name: discoveryserver
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8010/eureka